/** Compatibility export; worker code should import `terrain/core`. */
export {
  DEFAULT_TERRAIN_MATERIAL_PALETTE,
  TERRAIN_MATERIAL_LAYERS,
  TERRAIN_MATERIAL_LAYER_COUNT,
  applyTerrainMacroVariation,
  evaluateTerrainMaterial,
  packTerrainMaterialWeights,
  sampleTerrainMacroVariation,
  terrainMaterialColorRgb,
  type ITerrainMaterialColorOptions,
  type ITerrainMaterialOptions,
  type ITerrainMaterialPalette,
  type ITerrainMaterialQuery,
  type ITerrainMaterialSample,
  type TerrainMaterialLayer,
  type TerrainMaterialPosition,
  type TerrainMaterialRgb,
  type TerrainMaterialWeights,
} from 'triangular-engine/terrain/core';
